<?php
function rental_scan_perm() {
  return array('scan ads', 'sales leads');
}
function rental_scan_menu() {
  return array(
    'scan' => array( 
        'access arguments' => array('access content'),  
        'page callback' => 'drupal_get_form',
        'page arguments' => array('rental_scan_form'),              
        'access arguments' => array('scan ads'),
        'title' => 'Scanning Competitive Ads',
        'type' => MENU_CALLBACK ),           
//    'scan/update' => array(
//        'access arguments' => array('access content'),
//        'page callback' => 'rental_scan_update',
//        'title' => 'Scanning Competitive Ads',
//        'type' => MENU_CALLBACK ),
    'ajax/get-ad_sources' => array(  
        'access arguments' => array('access content'),
        'page callback' => 'rental_get_pick_list',
        'page arguments' => array('lead_source', 'source'), 
        'type' => MENU_CALLBACK ),     
    'ajax/get-ad_contacts' => array(  
        'access arguments' => array('access content'),
        'page callback' => 'rental_get_pick_list',
        'page arguments' => array('lead', 'contact_info'),
        'type' => MENU_CALLBACK ) );     
}

// ----------------------------------------------------------------------------
function rental_scan_form(&$form_state) {
  $f = $form_state['values'];
  global $variables;
  jquery_ui_add('ui.datepicker');
  drupal_add_js('$(function() {$(".datepicker").datepicker();});','inline');
  drupal_add_js(drupal_get_path('module', 'rental_scan') . '/rental_scan.js');

  if (isset($form_state['scan']['searched'])) {
    variable_set('ad_date', rental_date_convert($f['ad_date']));
    variable_set('source', $f['source']);
    $form['instruct'] = array( '#value' => rental_scan_instructions(2) );
    $form['ad_date']  = array( '#type'  => 'value', '#value' => $f['ad_date'] );
    $form['source']   = array( '#type'  => 'value', '#value' => $f['source']  );
    $form['rent']     = array( '#type'  => 'value', '#value' => $f['rent']);
    $form['original'] = array( '#type'  => 'value', '#value' => $f['contact']);
    $form['contact']  = array( 
        '#autocomplete_path' => 'ajax/get-ad_contacts',  
        '#title' => t('Contact Info'),
        '#type' => 'textfield',
        '#default_value' => isset($f['contact'])? $f['contact'] : '',
        '#description' => t('Enter part of phone number or other info given') );
    $form['update']  = array(
             '#type' => 'submit', '#value' => t('Update Contact Info') );
    $form['ad-area'] = array( '#value' => rental_scan_get_ads($f) );
    $form['ad_copy'] = array(
         //   '#type'  => 'textarea', '#cols'  => 40, '#rows' => 3,
             '#type' => 'textfield',
        '#maxlength' => 2048,
            '#title' => t('Ad copy'),
      '#description' => t('Enter the ad verbatim.') );
    $form['focus']   = array(
            '#value' => '<script type="text/javascript">document.getElementById("edit-ad-copy").focus();</script>');
    $form['save']= array(
             '#type' => 'submit', '#value' => t('Save'));
    $form['cancel']  = array(
             '#type' => 'submit', '#value' => t('Cancel') ); }
  else {
    $form['instruct']   = array( '#value' => rental_scan_instructions(1) );
    $form['ad_date'] = array(
        '#type' => 'textfield', 
        '#title' => 'Ad Date', '#size'  => 8,
        '#attributes' => array('class' => 'datepicker'),
        '#default_value' => isset($f['ad_date'])?
             $f['ad_date'] : date('m/d/Y', variable_get('ad_date', time() )));
    $form['source'] = array( 
        '#autocomplete_path' => 'ajax/get-ad_sources',  
        '#title' => t('Ad Source'),
        '#type' => 'textfield',
        '#default_value' => isset($f['source'])?
             $f['source'] : variable_get('source', ''),
        '#description' => t('Enter source of ad placement') );
    $form['rent'] = array(
        '#type' => 'textfield', '#size'  => 4,
        '#title' => 'Rent', 
        '#default_value' => isset($f['rent'])? $f['rent'] : '' );
    $form['contact'] = array( 
        '#autocomplete_path' => 'ajax/get-ad_contacts',  
        '#title' => t('Contact Info'),
        '#type' => 'textfield',
        '#default_value' => isset($f['contact'])? $f['contact'] : '',
        '#description' => t('Enter part of phone number or other info given') );
    $form['focus']   = array(
            '#value' => '<script type="text/javascript">document.getElementById("edit-rent").focus();</script>');
    $form['search'] = array(
        '#type' => 'submit', '#value' => t('Search') );
    $form['finish']= array(
             '#type' => 'submit', '#value' => t('Finish')); }
  return $form;
}
function rental_scan_instructions($section) {
  if ($section == 1) { return 
     "<ul>\n"
   . "  <li>If available, type in last four digits of phone number. </li>\n"
   . "  <li>If phone number is found, select and press SEARCH. </li>\n"
   . "  <li>If number is not found, erase and enter all contact information"
   . "available, phone number first, including area code "
   . "ONLY if it is NOT local, then press SEARCH. </li>\n"
   . "  <li>If ad does not contain phone number, "
   . "type in any other available contact information. </li>\n"
   . "  <li>If information is found, select and press SEARCH.</li>\n "
   . "  <li>If none is found, enter all contact info and hit SEARCH.</li>\n"
   . "</ol>\n"; }
  else { return
     "<ul>\n"
   . "  <li>Update contact information to include all that is available, "
   . "then press UPDATE CONTACT INFORMATION.</li>\n"
   . "  <li>If ad is found and is EXACTLY the same, select it. </li>\n"
   . "  <li>If not found or it has been updated to include new information, " 
   . "copy ad EXACTLY as it is listed and select SAVE NEW AD.</li>\n"
   . "</ul>\n"; }
}

function rental_scan_form_validate(&$form, &$form_state) {
  $f = $form_state['values'];
  if ($f['op'] == 'Search') {
    $form_state['rebuild']  = TRUE;
    $form_state['scan']['searched'] = TRUE; }
  if ($f['op'] == 'Update Contact Info') {
    $form_state['rebuild']  = TRUE;
    $form_state['scan']['searched'] = TRUE;
    $s = "UPDATE { lead } SET contact_info = '%s' WHERE contact_info = '%s'";
    $r = db_query($s, $f['contact'], $f['original']);
  }
}
function rental_scan_form_submit($form, &$form_state) {
  global $user;
  $f = $form_state['values'];
  switch ($f['op']) {
    case 'Finish' :
      $s = "DELETE FROM {variable} WHERE name = 'source' or name = 'ad_date'";
      db_query($s);
      cache_clear_all('variables', 'cache');
      $form_state['redirect'] = 'user';
      break;
    case 'Cancel' :
      break;
    case 'Save' :  // scanner enters a list item # for existing ad instead of ad copy
      $ac  = trim($f['ad_copy']);
      $aid = (strlen($ac) > 0 and strlen($ac) < 3) ?
             rental_scan_get_ads($f, $ac)
           : rental_insert_new_lead_ad($f);
      rental_insert_lead_ad_date($aid, rental_date_convert($f['ad_date']));
      break;
  }
}
//function rental_scan_update($aid, $date) {
//  rental_insert_lead_ad_date($aid, $date);
//  return drupal_get_form('rental_scan_form');
//}
function rental_insert_new_lead_ad($f) {
  global $user;
  $lid = rental_insert_when_new('lead','lid','contact_info',$f['contact']);
  $sid = rental_insert_when_new('lead_source','sid','source',$f['source']);
  $i = "INSERT INTO {lead_ad} (uid,lid,sid,rent,ad_copy) VALUES (%d,%d,%d,%d,'%s')";
  db_query($i, $user->uid, $lid, $sid, (int) $f['rent'], $f['ad_copy']);
  $s = "SELECT aid FROM {lead_ad}"
     . " WHERE lid = %d AND sid = %d AND ad_copy = '%s'";
  return  db_result(db_query($s, $lid, $sid, $f['ad_copy']));
}
function rental_insert_lead_ad_date($aid, $date) {
  global $user;
  if (!($date > 1000000)) { return; } // temporary fix
  $i = "INSERT INTO {lead_ad_date} (uid, aid, date) VALUES (%d, %d, %d)";
  $s = "SELECT COUNT(did) FROM {lead_ad_date} WHERE aid = %d AND date = %d";
  if ( !db_result(db_query($s, $aid, $date)) ) { // temporary fix
                  db_query($i, $user->uid, $aid, $date ); }
} 
function rental_scan_get_ads($f, $ac = NULL) {
  $d = variable_get('ad_date', time());
  $s = "SELECT * FROM {lead} l"
     . "         JOIN {lead_ad} a ON l.lid = a.lid"
     . " WHERE contact_info = '%s' and rent = %d"
     . "   and sid = (SELECT sid FROM {lead_source} WHERE source = '%s')"
     . "   and EXISTS (SELECT 1 FROM {lead_ad_date} d"
     . "                WHERE d.aid = a.aid and d.date > %d)"
     . " ORDER BY a.aid DESC";
  $q = db_query($s, $f['contact'], (int) $f['rent'], $f['source'], time() - 15 * 24*60*60);
  while ($p = db_fetch_object($q)) {
    $i++;
    if ((int)$ac == $i) { return $p->aid; } // this line is used when updating the ad date
    $r[] = array("$i ", ' --- ', $p->ad_copy);}
  $a = array('id' => 'teasers', 'align' => 'center');
  $sh = array('Ad date', 'Source', 'Rent', 'Contact');
  $sd = array(array($f['ad_date'], $f['source'], $f['rent'], $f['contact']));
  $sa = array('id' => 'scan', 'align' => 'center');
  return theme('table', $sh, $sd, $sa) . theme('table', NULL, $r, $a);
}
